### ISSUE TITLE
Simple Linux installation.

### ISSUE THREAD

**Issue by alex5250** [mgropp/pdfjumbler#10]
I really enjoy using your project.. But sometimes I think some users that use Linux had difficulties to install it. 
There are two options . First is just forget, i thinks is not best solution. Second one is use script for installation. 
There are a [simple script ](https://github.com/alex5250/PdfJumbler-Installer-Linux)that installs the application with copy paste one command. If you like it you can publish it there and i will give any support for support that script. 
P.S Tested only on Ubuntu 21.04 and Debian 10.

**Comment by mgropp** [comment]
Hi Alex!

Thanks a lot for your input! So far I've been putting off the Linux installer question, because... well, there isn't that one "Linux". But I agree, it's probably a good idea to at least support Debian and Ubuntu.

(Oh, and I should probably mention that PdfJumbler is on Flathub thanks to @nbenitez, and I saw someone even created an AUR package for Arch a while back, but not sure if this is still maintained.)

-- Okay, so let's do this, at least for Ubuntu and similar systems!

If you want, you can send me a pull request, and we can put the files in the repo here.

There are a couple of changes I would ask you to make before:
  * I'd suggest putting your files in `/setup/ubuntu/`
  * The first line of the script should be `#!/bin/sh` (or possibly `#!/bin/bash`)
  * You could use something like `if ( ! which java > /dev/null 2>&1 )` to check if Java is installed and `exit 1` if it isn't.
  * Is `wget` installed on Ubuntu systems by default? Maybe we could use `curl -o` instead if it is not.
  * Use `mkdir -p`, then the script can be used for updates. Also, this line will need sudo. (I'd prefer to run the downloads without root permissions.)
  * wget should download the files to a temporary directory (`mktemp -d`) that's deleted when we're done (something like https://www.linuxjournal.com/content/use-bash-trap-statement-cleanup-temporary-files would be great!)
  * The `/usr/bin/pdfjumbler` script should probably go to `/usr/local/bin`, and I'd propose something like this:
```
#!/bin/sh
exec java -jar /opt/pdfjumbler/pdfjumbler.jar "$@"
```
  * Permissions: I'd probably go for `chown root:root` for all files and directories and use 755 for directories and the start script, 644 for the rest.

**Comment by alex5250** [comment]
P.S it will nice to add icon also to application . Also as one as idea  is having flag -u for uninstallation

**Comment by alex5250** [comment]
Done :) Had [look](https://github.com/alex5250/PdfJumbler-Installer-Linux) . And can you give permissions to write in repo pls or upload files by your own .

**Comment by mgropp** [comment]
Thanks a lot!

A few comments:
  * Only use sudo where we actually need it
  * Use `mktemp -d` to make sure we're not overwriting something
  * The shell script needs a #! header
  * The quotation marks for the shell script line look wrong
  * `chmod -R` is only needed when you want to make recursive changes to directories
  * chown
  * Directory permissions
  * 755 only for executables and directories
  * The names should be consistently pdfjumbler, not pdf-jumbler

Please test the script thoroughly, and just send me a pull request when you're done! :)

**Comment by alex5250** [comment]
Still in progress ,but is fixed again :  P.S without sudo curl do not make any file in tmp dir . that is strange 
``Bash 
#!/bin/bash
# By Alex Zaslavskis.

echo Java should be installed on your system...
if command -v java >/dev/null 2>&1 ; then
    echo "java found"
    echo "version: $(java -version)"
else
    echo "java not found. Please install java"
    exit 1
fi




echo Clone all files 
 curl   https://raw.githubusercontent.com/alex5250/PdfJumbler-Installer-Linux/main/config.config  -L  -o /tmp/pdfjumbler.desktop

sudo mv /tmp/pdfjumbler.desktop /usr/share/applications/pdfjumbler.desktop
sudo chmod  644  /usr/share/applications/pdfjumbler.desktop
mkdir -p /opt/pdfjumbler

DOWNLOAD_URL=$(curl  https://api.github.com/repos/mgropp/pdfjumbler/releases/latest \
        | grep browser_download_url \
        | grep .jar \
        | cut -d '"' -f 4)
sudo curl  -L  -o /tmp/pdfjumbler.jar   "$DOWNLOAD_URL"
 sudo mv /tmp/pdfjumbler.jar /opt/pdfjumbler/pdfjumbler.jar
sudo chmod  755  /opt/pdfjumbler/pdfjumbler.jar
echo "exec java -jar /opt/pdfjumbler/pdfjumbler.jar "$@" " > /tmp/pdfjumbler.sh

sudo mv /tmp/pdfjumbler.sh /usr/local/bin/pdfjumbler


sudo chmod 755 /usr/local/bin/pdfjumbler



echo Done ...Enjoy

**Comment by alex5250** [comment]
Hello I finnaly make pull request , so had look and if you like it approve pls.
But we alos need update link to .config file that it fetchs from github .

**Comment by mgropp** [comment]
Hi Alex!
I added the things I had suggested previously and merged your commit.
I still have to test this on an Ubuntu machine, would be great if you could also give it a try!
And thanks again! :)

**Comment by alex5250** [comment]
Thanks so much . On my Ubuntu 21.04 it works .

**Comment by mgropp** [comment]
That's great to hear, thanks for testing! :)
